logging:
  level:
    ROOT: INFO
    org.jeejeejango: DEBUG
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.hibernate: INFO


spring:
  application:
    name: JPA Hibernate MutiTenant Sample

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.use_second_level_cache: false

  liquibase:
    change-log: classpath:/config/liquibase/changelog-master.xml
    enabled: false


tenant:
  default-tenant-id: tenant_1
  liquibase-enabled: true
  data-sources:
    -
      tenant-id: tenant_1
      url: jdbc:h2:file:./target/h2/tenant_1;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
    -
      tenant-id: tenant_2
      url: jdbc:h2:file:./target/h2/tenant_2;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      driver-class-name: org.h2.Driver